update

diff --git a/super_user b/super_user
--- a/super_user
+++ b/super_user
@@ -2,6 +2,9 @@
 REPO_DIR="$(dirname "$(readlink -m "${0}")")"
 user_current=$(logname)
 mkdir -p $REPO_DIR/logs $REPO_DIR/data_prepared
+YELLOW='\033[1;33m'
+GREEN='\033[1;32m'
+NC='\033[0m' # Không màu
 
 wifi() {
     cd "$REPO_DIR/wifi" || return
@@ -58,15 +61,24 @@ system() {
 
 prepared() {
     cd $REPO_DIR/data_prepared
-    # themes
-    git clone https://github.com/vinceliuice/WhiteSur-gtk-theme.git
-    # icons
-    git clone https://github.com/vinceliuice/WhiteSur-icon-theme.git
-    # cursors
-    git clone https://github.com/vinceliuice/WhiteSur-cursors.git
-    # fonts
-    wget $(curl -s https://api.github.com/repos/tonsky/FiraCode/releases/latest | grep browser_download_url | cut -d '"' -f 4) -O fira-code.zip
-    unzip fira-code.zip -d fira-code
+    repos=(
+        "https://github.com/vinceliuice/WhiteSur-gtk-theme.git"
+        "https://github.com/vinceliuice/WhiteSur-icon-theme.git"
+        "https://github.com/vinceliuice/WhiteSur-cursors.git"
+        "https://github.com/dracula/gnome-terminal"
+    )
+    for repo in "${repos[@]}"; do
+        sudo -u "$user_current" git clone "$repo"
+    done
+    # Download và giải nén fonts
+    font_url=$(curl -s https://api.github.com/repos/tonsky/FiraCode/releases/latest | grep browser_download_url | cut -d '"' -f 4)
+    sudo -u "$user_current" wget -q "$font_url" -O fira-code.zip
+    sudo -u "$user_current" unzip -q fira-code.zip -d fira-code
+    # Download oh-my-zsh install script
+    sudo -u "$user_current" wget -q https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
+    # Download gnome extensions install script
+    sudo -u "$user_current" wget -N -q "https://raw.githubusercontent.com/ToasterUwU/install-gnome-extensions/master/install-gnome-extensions.sh" -O ./install-gnome-extensions.sh
+    sudo -u "$user_current" chmod +x install-gnome-extensions.sh
 }
 
 softwares() {
@@ -77,9 +89,20 @@ softwares() {
     }
     gcm() {
         cd $REPO_DIR/data_prepared/
-        curl -s https://api.github.com/repos/git-ecosystem/git-credential-manager/releases/latest | grep "browser_download_url" | grep -v "symbol" | grep "linux" | grep "tar.gz" | cut -d : -f 2,3 | tr -d \" | wget -i -
-        gcm_file=$(ls gcm*.tar.gz)
-        tar -xvf $gcm_file -C /usr/local/bin
+        gcm_install() {
+            curl -s https://api.github.com/repos/git-ecosystem/git-credential-manager/releases/latest | grep "browser_download_url" | grep -v "symbol" | grep "linux" | grep "tar.gz" | cut -d : -f 2,3 | tr -d \" | wget -i -
+            gcm_file=$(ls gcm*.tar.gz)
+            tar -xvf $gcm_file -C /usr/bin
+            git-credential-manager configure
+        }
+        if [ command -v git-credential-manager ] &>/dev/null; then
+            git-credential-manager unconfigure
+            sudo rm -rf $(command -v git-credential-manager)
+            gcm_install
+        else
+            gcm_install
+        fi
+        git config --global credential.credentialStore secretservice
     }
     warp() {
         curl -fsSl https://pkg.cloudflareclient.com/cloudflare-warp-ascii.repo | tee /etc/yum.repos.d/cloudflare-warp.repo
@@ -164,27 +187,61 @@ gdms() {
     for setting in "${settings[@]}"; do
         sudo -u gdm dbus-launch gsettings set $setting
     done
-    sudo cp $REPO_DIR/gdms/custom.conf /etc/gdm
+    cp $REPO_DIR/gdms/custom.conf /etc/gdm
 }
 
-# users() {
-
-# }
-
-progress() {
-    echo "Task 1: Start"
-
-    echo -e "\033[A\033[KTask 1: Done"
-    echo "Task 2: Start"
-
-    echo -e "\033[A\033[KTask 2: Done"
-
+terminal() {
+    cd "$REPO_DIR/data_prepared/gnome-terminal" || exit
+    id=$(sudo -u "$user_current" gsettings get org.gnome.Terminal.ProfilesList default | tr -d "'")
+    profile_path="org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$id/"
+    keybindings_path="org.gnome.Terminal.Legacy.Keybindings:/org/gnome/terminal/legacy/keybindings/"
+    keybindings=(
+        "copy '<Ctrl>C'" "new-tab '<Ctrl>T'" "new-window '<Ctrl>N'" "save-contents '<Ctrl>S'"
+        "close-tab '<Ctrl>W'" "close-window '<Ctrl>Q'" "copy-html '<Ctrl>X'" "paste '<Ctrl>V'"
+        "select-all '<Ctrl>A'" "preferences '<Ctrl>P'" "find '<Ctrl>F'" "find-next '<Ctrl>G'"
+        "find-previous '<Ctrl>H'" "find-clear '<Ctrl>J'"
+    )
+    profile=(
+        "visible-name '$user_current'" "cursor-shape 'ibeam'"
+    )
+    for binding in "${keybindings[@]}"; do
+        sudo -u "$user_current" gsettings set $keybindings_path $binding
+    done
+    for setting in "${profile[@]}"; do
+        sudo -u "$user_current" gsettings set $profile_path $setting
+    done
+    sudo -u "$user_current" gsettings set org.gnome.desktop.interface enable-hot-corners false
+    sudo -u "$user_current" ./install.sh -s Dracula -p "$user_current" --skip-dircolors
+    for file in .zshrc .spaceshiprc.zsh; do
+        sudo -u "$user_current" cp "$REPO_DIR/create_users/$file" "/home/$user_current/$file"
+    done
 }
-# wifi &>/home/"$1"/Drive/logs/wifi.log
-system "$1" &>$REPO_DIR/logs/system.log
-# softwares &>/home/"$1"/Drive/logs/softwares.log
-# bootloader &>/home/"$1"/Drive/logs/bootloader.log
-themes &>$REPO_DIR/logs/themes.log
-fonts &>$REPO_DIR/logs/fonts.log
 
-echo $REPO_DIR
+check_and_run() {
+    local task_name="$1"
+    local log_file="$REPO_DIR/logs/$task_name.log"
+
+    if grep -q "Task completed" "$log_file" 2>/dev/null; then
+        echo "$task_name already completed, skipping."
+        echo -ne ""
+    else
+        echo -e "${YELLOW}Task $task_name: Start${NC}"
+        if $task_name &>"$log_file"; then
+            echo -e "\033[A\033[K${GREEN}Task $task_name: Done${NC}"
+            echo "Task completed" >>"$log_file"
+        else
+            echo "Task $task_name encountered an error. Check $log_file for details."
+            exit 1
+        fi
+    fi
+}
+
+# Danh sách các hàm cần chạy
+tasks=("wifi" "system" "prepared" "softwares" "bootloader" "themes" "fonts")
+
+# Chạy từng hàm và kiểm tra trạng thái
+for task in "${tasks[@]}"; do
+    check_and_run "$task"
+done
+
+echo "All tasks completed successfully."
